const Router = require('express')
const router = new Router()
const bookRouter = require('./bookRouter')
const janrRouter = require('./janrRouter')
const userRouter = require('./userRouter')
const authorRouter = require('./authorRouter')
const orderRouter = require('./orderRouter')
const contactsRouter = require('./contactsRouter')
const aboutRouter=require('./aboutRouter')
const adminRouter = require('./adminRouter')
const profileRouter = require('./profileRouter')
const orderBookRouter = require('./orderBookRouter')
const allOrdersRouter = require('./allOrdersRouter')
const manageBookRouter = require('./manageBookRouter')

router.use('/user', userRouter)
router.use('/janr', janrRouter)
router.use('/author', authorRouter)
router.use('/book', bookRouter)
router.use('/order', orderRouter)
router.use('/contacts', contactsRouter)
router.use('/about',aboutRouter)
router.use('/admin_shop', adminRouter)
router.use('/profile',profileRouter)
router.use('/order_book',orderBookRouter)
router.use('/allOrders', allOrdersRouter)
router.use('/manageBook',manageBookRouter)

module.exports = router